# Generated by Django 5.1.6 on 2025-03-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='uploaded_by',
            new_name='uploaded_by_id',
        ),
    ]
