# Generated by Django 5.1.6 on 2025-03-04 17:41

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(default=apps.accounts.models.generate_invite_code, max_length=16, unique=True),
        ),
    ]
